site_name: HSR Notizen FS17
site_url: https://doc.robinsuter.ch
repo_url: https://github.com/Excape/hsr-docs-fs17
site_description: HSR Study Documentation FS16
site_author: Robin Suter
copyright: 'Copyright (c) 2017 Robin Suter'

theme: 'material'

pages:
    - Home: 'index.md'
    - Dbs2:
        - 0 Index: 'Dbs2/0_Index.md'
        - 1 Exam Notes: 'Dbs2/1_Exam.md'
        - 2 OR-Mapping: 'Dbs2/2_OR-Mapping.md'
        - 3 Stored Procedures: 'Dbs2/3_Stored_Procedures.md'
        - 4 Triggers: 'Dbs2/4_Triggers.md'
        - 5 Views: 'Dbs2/5_Views.md'
        - 6 Datenstrukturen: 'Dbs2/6_Datenstrukturen.md'
        - 7 Interne Ebene: 'Dbs2/8_Interne_Ebene.md'
        - 8 Optimierung: 'Dbs2/9_Optimierung.md'
        - 9 Verteilte Datenbanken: 'Dbs2/10_Verteilte_DB.md'
        - 10 Replikation: 'Dbs2/11_Replikation.md'
        - 11 NoSQL: 'Dbs2/12_NoSQL.md'
        - 12 ObjectDBMS: 'Dbs2/13_ObjectDBMS.md'
        - 13 OR-DBMS: 'Dbs2/14_OR-DBMS.md'
        - 14 Column-Store DBMS: 'Dbs2/15_Column-Store_DBMS.md'
    - InfSi3:
        - 0 Index.md: 'InfSi3/0_Index.md'
        - 1 Exam.md: 'InfSi3/1_Exam.md'
        - 2 Overview.md: 'InfSi3/2_Overview.md'
        - 3 Software Security.md: 'InfSi3/3_Software_Security.md'
        - 4 Application Security Basics.md: 'InfSi3/4_Application_Security_Basics.md'
        - 5 SQL Injection.md: 'InfSi3/5_SQL_Injection.md'
        - 6 XSS.md: 'InfSi3/6_XSS.md'
        - 7 CORS.md: 'InfSi3/7_CORS.md'
        - 8 CSP.md: 'InfSi3/8_CSP.md'
        - 9 JSON Hijacking.md: 'InfSi3/9_JSON_Hijacking.md'
        - 10 CSRF.md: 'InfSi3/10_CSRF.md'
        - 11 Mobile Security.md: 'InfSi3/11_Mobile_Security.md'
        - 12 Web App Firewall.md: 'InfSi3/12_Web_App_Firewall.md'
        - 13 Server Security.md: 'InfSi3/13_Server_Security.md'
        - 14 Fraud Detection.md: 'InfSi3/14_Fraud_Detection.md'
        - 15 Security-Testing.md: 'InfSi3/15_Security-Testing.md'
        - 16 IAM.md: 'InfSi3/16_IAM.md'
        - 17 Mass Assigment.md: 'InfSi3/17_Mass_Assigment.md'
    - ITBus:
        - 0 Index: 'ITBus/0_Index.md'
        - 1 Exam Notes: 'ITBus/1_Exam.md'
        - 2 Informationssysteme: 'ITBus/2_Informationssysteme.md'
    - ParProg:
        - 0 Index: 'ParProg/0_Index.md'
        - 1 Exam Notes: 'ParProg/1_Exam.md'
        - 2 Multi-Threading Grundlagen: 'ParProg/2_Multi-Threading_Grundlagen.md'
        - 3 Thread Synchronisation: 'ParProg/3_Thread-Synchronisation.md'
        - 4 Synchronisationsprimitiven: 'ParProg/4_Synchronisationsprimitiven.md'
        - 5 Gefahren der Nebenl채ufigket: 'ParProg/5_Gefahren.md'
        - 6 Thread Pools: 'ParProg/6_Thread_Pools.md'
        - 7 Task Parallel Library: 'ParProg/7_Task_Parallel_Library.md'
        - 8 GUI Threading: 'ParProg/8_GUI_Threading.md'
        - 9 Memory Models: 'ParProg/9_Memory_Models.md'
        - 10 Actor Model: 'ParProg/10_Actor_Model.md'
        - 11 GPU Parallelisierung: 'ParProg/11_GPU_Parallelisierung.md'
        - 12 Cluster Parallelisierung: 'ParProg/12_Cluster_Parallelisierung.md'
        - 13 Reactive Programming: 'ParProg/13_Reactive_Programming.md'
        - 14 Software Transactional Memory: 'ParProg/14_Software_Transactional_Memory.md'
        - 15 Summary: 'ParProg/15_Summary.md'
    - PhAI:
        - 0 Index: 'PhAI/0_Index.md'
        - 1 Exam: 'PhAI/1_Exam.md'
    - SE2:
        - 0 Index: 'SE2/0_Index.md'
        - 1 Exam Notes: 'SE2/1_Exam.md'
        - 2 Project Automation: 'SE2/2_Project_Automation.md'
        - 3 Software Engineering Practises: 'SE2/3_SE_Practises.md'
        - 4 Error Handling Design: 'SE2/4_Error_Handling_Design.md'
        - 5 Design by Contract: 'SE2/5_Design_by_Contract.md'
        - 6 Story Splitting: 'SE2/6_Story_Splitting.md'
        - 7 Testing: 'SE2/7_Testing.md'
        - 8 Metriken: 'SE2/8_Metriken.md'
        - 9 Code Reviews: 'SE2/9_Code_Reviews.md'
        - 10 Performance-Messungen: 'SE2/10_Performance-Messungen.md'
        - 11 Usability Testing: 'SE2/11_Usability_Testing.md'
        - 12 Software Architecture: 'SE2/12_Software_Architecture.md'
        - 13 Scrum II: 'SE2/13_Scrum_2.md'
        - 14 Projektmanagement II: 'SE2/14_Projektmanagement_2.md'
        - 15 Correctness: 'SE2/15_Correctness.md'
    - VSS:
        - 0 Index: 'Vss/0_Index.md'
        - 1 Exam Notes: 'Vss/1_Exam.md'
        - 2 Introduction: 'Vss/2_Introduction.md'
        - 3 Socket Programmierung: 'Vss/3_socket_programmierung.md'
        - 4 Asynchronous Messaging: 'Vss/4_Asynchronous_Messaging.md'
        - 5 RMI and Web-Services: 'Vss/5_RMI_Web-Services.md'
        - 6 Design for Performance: 'Vss/6_Design_for_Performance.md'
        - 7 Scalability and Availability: 'Vss/7_Scalability_Availability.md'
        - 8 VSS Management: 'Vss/8_Vss_Management.md'
        - 9 CFIA: 'Vss/9_CFIA.md'
        - 10 Naming: 'Vss/10_Naming.md'
        - 11 Distributed Hash Tables: 'Vss/11_Distributed_Hash_Tables.md'
        - 12 Synchronization: 'Vss/12_Synchronization.md'
        - 13 Bitcoin: 'Vss/13_Bitcoin.md'
    - VWL:
        - 0 Index: 'Vwl/0_Index.md'
        - 1 Exam Notes: 'Vwl/1_Exam.md'
        - 2 Wohlstand: 'Vwl/2_Wohlstand.md'
        - 3 Einkommensverteilung und Sozialwerke: 'Vwl/3_Einkommensverteilung_und_Sozialwerke.md'
        - 4 Wachstum: 'Vwl/4_Wachstum.md'
        - 5 Arbeitsmarkt: 'Vwl/5_Arbeitsmarkt.md'
        - 6 Konjuktur: 'Vwl/6_Konjuktur.md'
        - 7 Preisstabilit채t: 'Vwl/7_Preisstabilit채t.md'
        - 8 Geld: 'Vwl/8_Geld.md'
        - 9 Wechselkurse: 'Vwl/9_Wechselkurse.md'
        - 10 Staatsfinanzen: 'Vwl/10_Staatsfinanzen.md'
        - 11 Banken: 'Vwl/11_Banken.md'
        - 12 Finanzkrise: 'Vwl/12_Finanzkrise.md'
        - 13 Markt und Preise: 'Vwl/13_Markt_und_Preise.md'
        - 14 Arbeitsteilung: 'Vwl/14_Arbeitsteilung.md'
        - 15 Europ채ische Integration: 'Vwl/15_Europaeische_Integration.md'


markdown_extensions:
  - toc
  - sane_lists
  - admonition
  - mdx_math
  - codehilite
  

extra:
    palette:
        primary: 'red'
        accent: 'amber'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    author:
        github: 'excape'
        twitter: 'robin_suter'

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_SVG

extra_css: [extra.css]
